---
title: ""

---
<style> body {text-align: justify} </style>
#
#
#
## About me:
#
I am a botanist with great passion for evolutionary biology and biogeography. My daily work consists of investigating (1) why some plant species are where they are and look how they look and then (2) why some areas and clades are much more species-rich than others.

Because these questions are multidisciplinary in nature, I have combined three main lines of research along my career to address them (see also *publications* for examples). 

**(1) Lineage-focused studies (systematics)**: What are the relationships among the species of flowering plants? Myrtaceae is the family I know best and have most contributed to, but I am very much interested in other lineages too.

**(2) Area-focused studies (biogeography)**: Where do these species occur? The neotropics is the area I understand best, but I have been also very interested in global patterns, especially involving environmental (abiotic) variables (e.g. altitude, climate, soils, etc).

**(3) Trait-focused studies (morphology and trait-evolution)**: What traits characterize these lineages? Floral traits are probably the ones I know best, but I have been really interested in traits related to dispersal (fruits, seeds) and survival (habit, leaves) recently.

I am particularly interested in questions that integrate the three topics described above. For instance, what are the spatial gradients of diversity and what cause them? Why some traits are more common in some areas and how these trait-area combinations drive distribution and diversification of flowering plants through time?

What underpins these questions is the inference of increasingly robust phylogenetic trees, larger trait and distribution datasets and the development of new comparative and macroevolutionary methods that incorporate better the complexity of biological evolution. Development of new methods and analyses of large datasets to answer these questions decribe well the aims of my current project as a postdoc at the Beaulieu lab.

